### ISSUE TITLE
Multiplayer Bug - Card not shown on grid

### ISSUE THREAD

**Issue by akamdar89** [nims92/IndianCardBattle#1]
![WhatsApp Image 2023-03-11 at 19 50 40](https://user-images.githubusercontent.com/63495967/224489839-75f58b74-f5f0-47a8-929e-e7b6408fe1c9.jpg)
![WhatsApp Image 2023-03-10 at 23 58 16](https://user-images.githubusercontent.com/63495967/224489843-e40163f0-f0ce-454e-8c7e-4d3359fa705d.jpg)

One Kaurava card not showing on opponent's side for some reason. 
(Second screenshot - 3rd location)

**Comment by nims92** [comment]
Fixed
