### ISSUE TITLE
Hastinapur location ability 

### ISSUE THREAD

**Issue by akamdar89** [nims92/IndianCardBattle#14]
Location Ability needs to add power to the card. 

This is mainly so Arjuna can be activated when a 4 power card gets +5. 

Currently power gets added to the location calculation and not to the card placed there.

![image](https://user-images.githubusercontent.com/63495967/228759871-ca45ff26-bc89-4b10-ad23-4c59a522540b.png)

**Comment by nims92** [comment]
@akamdar89 Can you share a video from Snap demonstrating the same?

**Comment by nims92** [comment]
Implemented.
