### ISSUE TITLE
Takshashila should not fill location with cards if not played there 

### ISSUE THREAD

**Issue by akamdar89** [nims92/IndianCardBattle#18]
Vrindavan moved cards one location right. 

Takhshashila had no cards there - as soon as one card moved - it duplicated to fill full location.

**Comment by nims92** [comment]
This is expected in a case where Vrindavan's ability is executed before Takhshashila's ability.

**Comment by akamdar89** [comment]
Not expected because it only applies when a card is directly intentionally PLAYED there. Never when moved.

**Comment by nims92** [comment]
Implemented as per suggestion.
