### ISSUE TITLE
Karna ability + Hastinapur transfers to new location on move

### ISSUE THREAD

**Issue by akamdar89** [nims92/IndianCardBattle#20]
![WhatsApp Image 2023-04-16 at 21 07 14](https://user-images.githubusercontent.com/63495967/232324040-e9048292-c201-4648-98c4-8bc17282247f.jpg)

Karna played on Hastinapur at turn 4, after that location moved all cards right. 

Score for Magadh should be 11 not 16.

**Comment by nims92** [comment]
Fixed
