### ISSUE TITLE
Gameplay BG is too zoomed in

### ISSUE THREAD

**Issue by akamdar89** [nims92/IndianCardBattle#7]
![image](https://user-images.githubusercontent.com/63495967/228543431-de77ce82-2221-437c-9c7d-9162221ad762.png)

![image](https://user-images.githubusercontent.com/63495967/228543559-1a96c675-5fd4-4e23-a670-33a253c9e81d.png)

![image](https://user-images.githubusercontent.com/63495967/228550663-0178f84e-4599-4fa1-9c51-3988c92f4800.png)

**Comment by akamdar89** [comment]
![image](https://user-images.githubusercontent.com/63495967/228545919-1d703298-e012-47c9-b99c-838ea4315a2a.png)

![image](https://user-images.githubusercontent.com/63495967/228546018-c5ca6cc9-c349-4caa-bbf1-ead1db414bd0.png)


BG should look like this ideally

**Comment by nims92** [comment]
Implemented.
