### ISSUE TITLE
Game stuck after turn 4 

### ISSUE THREAD

**Issue by akamdar89** [nims92/IndianCardBattle#9]
![image](https://user-images.githubusercontent.com/63495967/228544855-cdeb1ee9-c1ea-41d8-a95f-37fd832a1449.png)
![image](https://user-images.githubusercontent.com/63495967/228544877-25c69d9e-8c5c-4f27-b4b6-c7a5cf95deb5.png)

Player Duryodhana into Takshashila as last move, game not progressing after that. Turn 4 unplayable.

**Comment by akamdar89** [comment]
![image](https://user-images.githubusercontent.com/63495967/228545306-a20ac2b4-91c3-44ce-9706-f0572e75493a.png)

**Comment by nims92** [comment]
Implemented.
